language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ajith/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true ajith/docker-react npm run test
  
